const generateReviews = (trainerName: string) => [
  { 
    _id: Math.random().toString(), 
    userId: { name: "Sarah K.", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop" }, 
    rating: 5, 
    date: "Oct 12, 2025", 
    review: `Working with ${trainerName} was a game changer for my fitness journey. I learned so much about proper form and nutrition.`, 
    helpfulCount: 24, 
    verifiedClient: true, 
    trainerReply: "Thank you Sarah! Keep crushing it!" 
  },
  { 
    _id: Math.random().toString(), 
    userId: { name: "Mike T.", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop" }, 
    rating: 4, 
    date: "Sep 28, 2025", 
    review: "Great programming, very challenging but I see the results.", 
    helpfulCount: 12, 
    verifiedClient: true 
  },
  { 
    _id: Math.random().toString(), 
    userId: { name: "Elena V.", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop" }, 
    rating: 5, 
    date: "Aug 15, 2025", 
    review: "Absolutely incredible experience. Pushed me past my mental barriers.", 
    helpfulCount: 45, 
    verifiedClient: true,
    trainerReply: "You did the hard work Elena! Proud of you."
  }
];

const generateTransformations = () => [
  { 
    id: Math.random().toString(), 
    beforeImage: "https://images.unsplash.com/photo-1608222351212-18fe0ec7b13b?w=600&h=800&fit=crop", 
    afterImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=800&fit=crop", 
    clientName: "David M.", 
    duration: "12 Weeks", 
    goalAchieved: "Fat Loss & Muscle Definition", 
    weightChange: "-18 lbs", 
    testimonial: "The programming was brutal but effective. I've completely transformed my lifestyle." 
  },
  { 
    id: Math.random().toString(), 
    beforeImage: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=800&fit=crop", 
    afterImage: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&h=800&fit=crop", 
    clientName: "Jessica R.", 
    duration: "8 Weeks", 
    goalAchieved: "Strength & Toning", 
    weightChange: "-8 lbs", 
    testimonial: "I've never felt stronger or more confident in my body." 
  }
];

const generateSchedule = (variant: number) => {
  if (variant === 1) return { Monday: '09:00 - 17:00', Tuesday: 'Booked', Wednesday: '09:00 - 14:00', Thursday: 'Available', Friday: '09:00 - 18:00', Saturday: 'Limited Slots', Sunday: 'Off' };
  if (variant === 2) return { Monday: 'Available', Tuesday: '08:00 - 12:00', Wednesday: 'Booked', Thursday: '08:00 - 16:00', Friday: 'Limited Slots', Saturday: '09:00 - 15:00', Sunday: 'Available' };
  return { Monday: 'Booked', Tuesday: 'Booked', Wednesday: '07:00 - 15:00', Thursday: 'Available', Friday: 'Available', Saturday: 'Off', Sunday: 'Off' };
};

export const MOCK_TRAINERS = [
  {
    _id: 'mock-trainer-1', id: 'mock-trainer-1',
    fullName: 'Alex Reynolds',
    specializations: ['Strength Training', 'Bodybuilding', 'Powerlifting'],
    experienceYears: 8,
    certifications: ['ISSA Certified Personal Trainer', 'Precision Nutrition Level 1'],
    languages: ['English', 'Spanish'],
    rating: 4.9,
    totalReviews: 124,
    biography: 'Elite strength coach specializing in functional hypertrophy and raw powerlifting. I believe in mastering the basics before adding complexity.',
    hourlyPrice: 4500,
    availabilityStatus: 'Offline',
    city: 'New York', country: 'USA',
    featuredTrainer: true,
    verifiedTrainer: true,
    profileImage: 'https://images.unsplash.com/photo-1567598508481-65985588ce6e?w=800&h=800&fit=crop',
    reviews: generateReviews('Alex'),
    transformations: generateTransformations(),
    stats: { clientsTrained: '300+', sessionsCompleted: '2.5k', yearsExperience: 8, successRate: '98%' },
    badges: ['Verified Coach', 'Top Rated', 'Premium Coach'],
    weeklySchedule: generateSchedule(1)
  },
  {
    _id: 'mock-trainer-2', id: 'mock-trainer-2',
    fullName: 'Sophia Chen',
    specializations: ['Yoga', 'Pilates', 'Flexibility'],
    experienceYears: 5,
    certifications: ['RYT 500 Yoga Alliance', 'Stott Pilates Certified'],
    languages: ['English', 'Mandarin'],
    rating: 4.8,
    totalReviews: 89,
    biography: 'Holistic movement specialist focusing on mind-body connection, core stability, and dynamic flexibility flows.',
    hourlyPrice: 3500,
    availabilityStatus: 'Online',
    city: 'Los Angeles', country: 'USA',
    featuredTrainer: false,
    verifiedTrainer: true,
    profileImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&h=800&fit=crop',
    reviews: generateReviews('Sophia'),
    transformations: generateTransformations(),
    stats: { clientsTrained: '150+', sessionsCompleted: '1.2k', yearsExperience: 5, successRate: '95%' },
    badges: ['Verified Coach', 'Trending'],
    weeklySchedule: generateSchedule(2)
  },
  {
    _id: 'mock-trainer-3', id: 'mock-trainer-3',
    fullName: 'Marcus Johnson',
    specializations: ['HIIT', 'Fat Loss', 'Sports Performance'],
    experienceYears: 10,
    certifications: ['NASM CPT', 'CSCS'],
    languages: ['English'],
    rating: 5.0,
    totalReviews: 210,
    biography: 'Former collegiate athlete turned performance coach. My high-intensity protocols guarantee maximum fat burn in minimum time.',
    hourlyPrice: 5000,
    availabilityStatus: 'Offline',
    city: 'Chicago', country: 'USA',
    featuredTrainer: true,
    verifiedTrainer: true,
    profileImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=800&fit=crop',
    reviews: generateReviews('Marcus'),
    transformations: generateTransformations(),
    stats: { clientsTrained: '500+', sessionsCompleted: '4k', yearsExperience: 10, successRate: '99%' },
    badges: ['Verified Coach', 'Premium Coach', 'Featured'],
    weeklySchedule: generateSchedule(3)
  },
  {
    _id: 'mock-trainer-4', id: 'mock-trainer-4',
    fullName: 'Elena Rodriguez',
    specializations: ['CrossFit', 'Functional Training', 'Nutrition'],
    experienceYears: 6,
    certifications: ['CrossFit Level 2', 'Precision Nutrition Level 2'],
    languages: ['English', 'Spanish'],
    rating: 4.7,
    totalReviews: 76,
    biography: 'Passionate about building functional fitness that translates to everyday life. I combine intense WODs with precise macro tracking.',
    hourlyPrice: 4000,
    availabilityStatus: 'Online',
    city: 'Miami', country: 'USA',
    featuredTrainer: false,
    verifiedTrainer: false,
    profileImage: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=800&h=800&fit=crop',
    reviews: generateReviews('Elena'),
    transformations: generateTransformations(),
    stats: { clientsTrained: '120+', sessionsCompleted: '900', yearsExperience: 6, successRate: '92%' },
    badges: ['Trending'],
    weeklySchedule: generateSchedule(1)
  },
  {
    _id: 'mock-trainer-5', id: 'mock-trainer-5',
    fullName: 'David Kim',
    specializations: ['Rehabilitation', 'Senior Fitness', 'Mobility'],
    experienceYears: 12,
    certifications: ['DPT', 'NASM Corrective Exercise Spec'],
    languages: ['English', 'Korean'],
    rating: 4.9,
    totalReviews: 156,
    biography: 'Bridging the gap between physical therapy and personal training. I help clients recover from injuries and build bulletproof joints.',
    hourlyPrice: 6000,
    availabilityStatus: 'Offline',
    city: 'Seattle', country: 'USA',
    featuredTrainer: true,
    verifiedTrainer: true,
    profileImage: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&h=800&fit=crop',
    reviews: generateReviews('David'),
    transformations: generateTransformations(),
    stats: { clientsTrained: '400+', sessionsCompleted: '3.5k', yearsExperience: 12, successRate: '97%' },
    badges: ['Verified Coach', 'Top Rated'],
    weeklySchedule: generateSchedule(2)
  },
  {
    _id: 'mock-trainer-6', id: 'mock-trainer-6',
    fullName: 'Aisha Patel',
    specializations: ['Women\'s Fitness', 'Pre/Postnatal', 'Core Strength'],
    experienceYears: 7,
    certifications: ['ACE CPT', 'PROnatal Certified'],
    languages: ['English', 'Hindi'],
    rating: 4.8,
    totalReviews: 112,
    biography: 'Dedicated to empowering women through all stages of life. Safe, effective training for mothers and mothers-to-be.',
    hourlyPrice: 3800,
    availabilityStatus: 'Online',
    city: 'London', country: 'UK',
    featuredTrainer: false,
    verifiedTrainer: true,
    profileImage: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&h=800&fit=crop',
    reviews: generateReviews('Aisha'),
    transformations: generateTransformations(),
    stats: { clientsTrained: '250+', sessionsCompleted: '2k', yearsExperience: 7, successRate: '96%' },
    badges: ['Verified Coach', 'Trending'],
    weeklySchedule: generateSchedule(3)
  },
  {
    _id: 'mock-trainer-7', id: 'mock-trainer-7',
    fullName: 'James Wilson',
    specializations: ['Cardio', 'Endurance', 'Triathlon Prep'],
    experienceYears: 9,
    certifications: ['Ironman Certified Coach', 'USATF Level 1'],
    languages: ['English'],
    rating: 4.6,
    totalReviews: 65,
    biography: 'Endurance specialist. Whether it is your first 5K or an Ironman, I will build the engine you need to cross the finish line.',
    hourlyPrice: 4200,
    availabilityStatus: 'Offline',
    city: 'Boulder', country: 'USA',
    featuredTrainer: false,
    verifiedTrainer: true,
    profileImage: 'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=800&h=800&fit=crop',
    reviews: generateReviews('James'),
    transformations: generateTransformations(),
    stats: { clientsTrained: '100+', sessionsCompleted: '800', yearsExperience: 9, successRate: '90%' },
    badges: ['Verified Coach'],
    weeklySchedule: generateSchedule(1)
  },
  {
    _id: 'mock-trainer-8', id: 'mock-trainer-8',
    fullName: 'Zara Khan',
    specializations: ['Pilates', 'Barre', 'Dance Fitness'],
    experienceYears: 4,
    certifications: ['Balanced Body Barre', 'Zumba Pro'],
    languages: ['English', 'Urdu'],
    rating: 4.7,
    totalReviews: 94,
    biography: 'Make fitness fun again! High-energy rhythm-based workouts that sculpt long, lean muscles while burning serious calories.',
    hourlyPrice: 3000,
    availabilityStatus: 'Online',
    city: 'Dubai', country: 'UAE',
    featuredTrainer: true,
    verifiedTrainer: true,
    profileImage: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800&h=800&fit=crop',
    reviews: generateReviews('Zara'),
    transformations: generateTransformations(),
    stats: { clientsTrained: '200+', sessionsCompleted: '1.8k', yearsExperience: 4, successRate: '94%' },
    badges: ['Verified Coach', 'Featured'],
    weeklySchedule: generateSchedule(2)
  }
];

export const getMockTrainerById = (id: string) => {
  return MOCK_TRAINERS.find(t => t.id === id || t._id === id);
};
