export const MOCK_TRAINERS = [
  {
    _id: "mock_t_01",
    fullName: "Marcus Reynolds",
    email: "marcus.reynolds@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1567598508481-65985588e295?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Strength Training", "Bodybuilding", "Nutrition Coaching"],
    rating: 4.9,
    totalReviews: 86,
    experienceYears: 8,
    certifications: ["NASM-CPT", "Precision Nutrition L1"],
    languages: ["English"],
    biography: "With over 8 years of experience in competitive bodybuilding, I focus on science-based hypertrophy and customized nutrition plans. Let's build your dream physique with sustainable habits.",
    hourlyPrice: 4500,
    availabilityStatus: "Online",
    featuredTrainer: true,
    verifiedTrainer: true,
    city: "New York",
    country: "USA",
    reviews: [
      { id: "r1", reviewerName: "James T.", avatar: "https://i.pravatar.cc/150?u=1", rating: 5, text: "Marcus changed my life. Period. The workouts are intense but manageable.", date: "2023-10-12", verified: true },
      { id: "r2", reviewerName: "Sarah M.", avatar: "https://i.pravatar.cc/150?u=2", rating: 5, text: "Unbelievable attention to detail in my nutrition plan.", date: "2023-11-05", verified: true },
      { id: "r3", reviewerName: "Mike R.", avatar: "https://i.pravatar.cc/150?u=3", rating: 4, text: "Great coach, pushes you hard. Sometimes a bit late to reply but worth it.", date: "2023-11-20", verified: true },
      { id: "r4", reviewerName: "David L.", avatar: "https://i.pravatar.cc/150?u=4", rating: 5, text: "Best PT I've ever had.", date: "2023-12-01", verified: true },
    ]
  },
  {
    _id: "mock_t_02",
    fullName: "Elena Rostova",
    email: "elena.r@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1609899517235-c32e1f417537?auto=format&fit=crop&w=1080&q=80",
    specializations: ["HIIT", "CrossFit", "Functional Training"],
    rating: 4.8,
    totalReviews: 64,
    experienceYears: 5,
    certifications: ["CrossFit Level 2", "ACE-CPT"],
    languages: ["English", "Russian"],
    biography: "Former gymnast turned CrossFit competitor. My programs are designed to test your limits, improve your cardiovascular capacity, and build functional strength that translates to real life.",
    hourlyPrice: 3500,
    availabilityStatus: "In-Person",
    featuredTrainer: true,
    verifiedTrainer: true,
    city: "London",
    country: "UK",
    reviews: [
      { id: "r1", reviewerName: "Emma W.", avatar: "https://i.pravatar.cc/150?u=5", rating: 5, text: "Elena's HIIT sessions are no joke. I'm in the best shape of my life.", date: "2023-09-15", verified: true },
      { id: "r2", reviewerName: "Chris B.", avatar: "https://i.pravatar.cc/150?u=6", rating: 5, text: "Very knowledgeable about proper form and injury prevention.", date: "2023-10-02", verified: true },
      { id: "r3", reviewerName: "Alex J.", avatar: "https://i.pravatar.cc/150?u=7", rating: 4, text: "Great energy, keeps me motivated.", date: "2023-10-28", verified: false },
    ]
  },
  {
    _id: "mock_t_03",
    fullName: "David Chen",
    email: "david.c@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Yoga", "Pilates", "Rehabilitation"],
    rating: 4.9,
    totalReviews: 112,
    experienceYears: 12,
    certifications: ["RYT-500", "Physical Therapy Assistant"],
    languages: ["English", "Mandarin"],
    biography: "Holistic movement coach specializing in mobility, injury rehab, and mindfulness. I help athletes and desk workers alike restore natural movement patterns and eliminate chronic pain.",
    hourlyPrice: 4000,
    availabilityStatus: "Online",
    featuredTrainer: false,
    verifiedTrainer: true,
    city: "San Francisco",
    country: "USA",
    reviews: [
      { id: "r1", reviewerName: "John D.", avatar: "https://i.pravatar.cc/150?u=8", rating: 5, text: "Fixed my lower back pain in 4 weeks.", date: "2023-08-10", verified: true },
      { id: "r2", reviewerName: "Lisa P.", avatar: "https://i.pravatar.cc/150?u=9", rating: 5, text: "Incredibly calming presence. The yoga sessions are magical.", date: "2023-09-22", verified: true },
    ]
  },
  {
    _id: "mock_t_04",
    fullName: "Sarah Jenkins",
    email: "sarah.j@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Fat Loss", "Women's Fitness"],
    rating: 4.7,
    totalReviews: 45,
    experienceYears: 4,
    certifications: ["ISSA-CPT"],
    languages: ["English"],
    biography: "I specialize in helping women regain their confidence through sustainable fat loss and strength training. No crash diets, just real results.",
    hourlyPrice: 2500,
    availabilityStatus: "In-Person",
    featuredTrainer: true,
    verifiedTrainer: true,
    city: "Chicago",
    country: "USA",
    reviews: [
      { id: "r1", reviewerName: "Amanda R.", avatar: "https://i.pravatar.cc/150?u=10", rating: 5, text: "Sarah is so supportive. I lost 15lbs and feel amazing.", date: "2023-11-11", verified: true },
    ]
  },
  {
    _id: "mock_t_05",
    fullName: "Jamal Washington",
    email: "jamal.w@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1583465573241-db401cebf18e?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Sports Performance", "Powerlifting"],
    rating: 5.0,
    totalReviews: 32,
    experienceYears: 10,
    certifications: ["CSCS", "USAW Level 1"],
    languages: ["English"],
    biography: "Former D1 athlete. I train athletes to jump higher, run faster, and lift heavier. If you want peak performance, you're in the right place.",
    hourlyPrice: 6000,
    availabilityStatus: "Online",
    featuredTrainer: false,
    verifiedTrainer: true,
    city: "Miami",
    country: "USA",
    reviews: [
      { id: "r1", reviewerName: "Tyler S.", avatar: "https://i.pravatar.cc/150?u=11", rating: 5, text: "Added 50lbs to my squat in 2 months. Jamal knows his stuff.", date: "2023-12-05", verified: true },
    ]
  },
  {
    _id: "mock_t_06",
    fullName: "Aisha Patel",
    email: "aisha.p@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Yoga", "Meditation"],
    rating: 4.9,
    totalReviews: 78,
    experienceYears: 7,
    certifications: ["E-RYT 200"],
    languages: ["English", "Hindi"],
    biography: "Find your balance. My classes blend Vinyasa flow with deep meditative practices to strengthen both mind and body.",
    hourlyPrice: 3000,
    availabilityStatus: "In-Person",
    featuredTrainer: false,
    verifiedTrainer: true,
    city: "Toronto",
    country: "Canada",
    reviews: [
      { id: "r1", reviewerName: "Priya K.", avatar: "https://i.pravatar.cc/150?u=12", rating: 5, text: "Truly transformative sessions.", date: "2023-10-18", verified: true },
    ]
  },
  {
    _id: "mock_t_07",
    fullName: "Lucas Silva",
    email: "lucas.s@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1563823297072-005d52033bc6?auto=format&fit=crop&w=1080&q=80",
    specializations: ["CrossFit", "Weightlifting"],
    rating: 4.8,
    totalReviews: 55,
    experienceYears: 6,
    certifications: ["CrossFit Level 1"],
    languages: ["English", "Portuguese"],
    biography: "High-intensity training focused on Olympic lifting techniques. Let's break your PRs.",
    hourlyPrice: 3500,
    availabilityStatus: "Online",
    featuredTrainer: false,
    verifiedTrainer: true,
    city: "Rio de Janeiro",
    country: "Brazil",
    reviews: []
  },
  {
    _id: "mock_t_08",
    fullName: "Isabella Martinez",
    email: "isabella.m@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Pilates", "Senior Fitness"],
    rating: 4.9,
    totalReviews: 41,
    experienceYears: 9,
    certifications: ["PMA-CPT"],
    languages: ["English", "Spanish"],
    biography: "Gentle yet highly effective core strengthening for all ages, with a special focus on senior mobility and joint health.",
    hourlyPrice: 3200,
    availabilityStatus: "In-Person",
    featuredTrainer: false,
    verifiedTrainer: true,
    city: "Madrid",
    country: "Spain",
    reviews: []
  },
  {
    _id: "mock_t_09",
    fullName: "Thomas Wright",
    email: "thomas.w@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Bodybuilding", "Fat Loss"],
    rating: 4.6,
    totalReviews: 29,
    experienceYears: 3,
    certifications: ["ACE-CPT"],
    languages: ["English"],
    biography: "I focus on aesthetics and body recomposition. If you want to look good at the beach, I'm your guy.",
    hourlyPrice: 2800,
    availabilityStatus: "Online",
    featuredTrainer: false,
    verifiedTrainer: false,
    city: "Sydney",
    country: "Australia",
    reviews: []
  },
  {
    _id: "mock_t_10",
    fullName: "Yuki Tanaka",
    email: "yuki.t@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=1080&q=80",
    specializations: ["HIIT", "Functional Training"],
    rating: 4.8,
    totalReviews: 92,
    experienceYears: 7,
    certifications: ["NASM-CPT"],
    languages: ["English", "Japanese"],
    biography: "Fast, efficient, and sweaty. My 30-minute HIIT routines are perfect for busy professionals who need maximum results in minimum time.",
    hourlyPrice: 3800,
    availabilityStatus: "Online",
    featuredTrainer: true,
    verifiedTrainer: true,
    city: "Tokyo",
    country: "Japan",
    reviews: []
  },
  {
    _id: "mock_t_11",
    fullName: "Olivia Brown",
    email: "olivia.b@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1611080183180-87a15ec97bc1?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Nutrition Coaching", "Fat Loss"],
    rating: 5.0,
    totalReviews: 105,
    experienceYears: 11,
    certifications: ["Registered Dietitian", "ISSA-CPT"],
    languages: ["English"],
    biography: "Abs are made in the kitchen. I provide comprehensive meal planning paired with effective exercise routines for sustainable weight loss.",
    hourlyPrice: 5000,
    availabilityStatus: "Online",
    featuredTrainer: true,
    verifiedTrainer: true,
    city: "Austin",
    country: "USA",
    reviews: []
  },
  {
    _id: "mock_t_12",
    fullName: "Omar Hassan",
    email: "omar.h@example.com",
    role: "trainer",
    profileImage: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=1080&q=80",
    specializations: ["Strength Training", "Sports Performance"],
    rating: 4.7,
    totalReviews: 38,
    experienceYears: 5,
    certifications: ["CSCS"],
    languages: ["English", "Arabic"],
    biography: "Specialized training for athletes preparing for their season. Agility, speed, and raw power.",
    hourlyPrice: 4200,
    availabilityStatus: "In-Person",
    featuredTrainer: false,
    verifiedTrainer: true,
    city: "Dubai",
    country: "UAE",
    reviews: []
  }
];

export const getMockTrainerById = (id: string) => {
  return MOCK_TRAINERS.find(t => t._id === id);
};
