export const FitnessRules = {
  MAINTENANCE_MALE_MULTIPLIER: 24,
  MAINTENANCE_FEMALE_MULTIPLIER: 22,
  SEDENTARY_ACTIVITY_MULTIPLIER: 1.2,
  
  PROTEIN_TARGET_PER_KG: 2.0, // 2g per kg of bodyweight
  
  ACWR_DANGER_THRESHOLD: 1.5,
  ACWR_WARNING_THRESHOLD: 1.3,
  
  BURNOUT_CRITICAL_THRESHOLD: 70,
  BURNOUT_WARNING_THRESHOLD: 40,
  
  HBI_OVERALL_WEIGHT: 0.4,
  HBI_DISCIPLINE_WEIGHT: 0.4,
  HBI_BODY_WEIGHT: 0.2,

  DEFAULT_WEIGHT_KG: 70,
  DEFAULT_MAINTENANCE_CALORIES: 2500,
  DEFAULT_PROTEIN_TARGET: 150
};
